### PR TITLE
add ts-node in dev dependecy

### PR DESCRIPTION
**Pull request by houssemAmiri**
this pull request is associated with this issue: https://github.com/yebrahim/codersquare/issues/15

### CODE REVIEW

**Review by yebrahim — COMMENTED** [review]
change looks good to me, why delete all these lines in package-lock though?

**Comment by houssemAmiri** [comment]
> change looks good to me, why delete all these lines in package-lock though?

@yebrahim  it's auto-generated by npm I didn't change anything,  does I shouldn't commit the package-lock.json ?

**Comment by yebrahim** [comment]
I'd just run `npm install` one more time inside the web directory, it's weird the file should get gutted like that by npm. :)

**Comment by houssemAmiri** [comment]
> he file should get gutted

so I will discard the package-lock.json changes

**Review by yebrahim — APPROVED** [review]

**Comment by yebrahim** [comment]
thanks @houssemAmiri.

**Pull request merged**
